name: Node setup

on:
  workflow_dispatch: # trigger manually

# globals
env:
 # meld
  MELD_CLIENTS_CORE_REPO: oerc-music/meld-clients-core
  MELD_CLIENTS_CORE_BRANCH: unblacking-newdeps
  MELD_CLIENTS_CORE_DIR: meld-clients-core
  MELD_HELLO_REPO: oerc-music/meld-hello-meld
  MELD_HELLO_BRANCH: main
  MELD_HELLO_DIR: meld-hello-meld

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Checkout MELD_CLIENTS_CORE_REPO into MELD_CLIENTS_CORE_DIR
      uses: actions/checkout@v2
      with:
        repository: ${{ env.MELD_CLIENTS_CORE_REPO }}
        ref: ${{ env.MELD_CLIENTS_CORE_BRANCH }}
        path: ${{ env.MELD_CLIENTS_CORE_DIR }}
    
    - name: Checkout MELD_HELLO_REPO into MELD_HELLO_DIR
      uses: actions/checkout@v2
      with:
        repository: ${{ env.MELD_HELLO_REPO }}
        ref: ${{ env.MELD_HELLO_BRANCH }}
        path: ${{ env.MELD_HELLO_DIR }}
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
 
    - name: Verify
      run: ls -Rl
 
    - name: Install dependencies of MELD_CLIENTS_CORE
      working-directory: ${{ env.MELD_CLIENTS_CORE_DIR }}
      run: npm ci
    
    - name: Install dependencies of MELD_HELLO
      working-directory: ${{ env.MELD_HELLO_DIR }}/hello-meld-3
      run: npm ci
  
    - name: Link node_modules of MELD_CLIENTS_CORE
      working-directory: ${{ env.MELD_CLIENTS_CORE_DIR }}
      run: npm link
  
    - name: Remove node_modules of MELD_CLIENTS_CORE
      working-directory: ${{ env.MELD_CLIENTS_CORE_DIR }}
      run: mv node_modules another_node_modules
    
    - name: Link node_modules from MELD_CLIENTS_CORE to MELD_HELLO
      working-directory: ${{ env.MELD_HELLO_DIR }}/hello-meld-3  
      run: npm link meld-clients-core
    
    - name: Check for node-modules
      working-directory: ${{ env.MELD_HELLO_DIR }}/hello-meld-3  
      run: ls -al node_modules/meld-clients-core  
    
    - name: Start
      working-directory: ${{ env.MELD_HELLO_DIR }}/hello-meld-3  
      run: npm start & npx wait-on http://localhost:8080
      env:
        CI: true

